openapi: 3.0.3
info:
  title: Media API
  description: Media
  version: "1"
servers:
  - url: 'http://localhost:8083'
tags:
  - name: media
paths:
  /media:
    post:
      tags:
        - media
      summary: upload a media by mediaId
      operationId: uploadMedia
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MediaUpload'
      responses:
        '200':
          description: successful upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaUploadResponse'

  /media/{mediaId}:
    get:
      tags:
        - media
      summary: download a media by mediaId
      operationId: downloadMedia
      parameters:
        - name: mediaId
          in: path
          description: id of media
          required: true
          schema:
            type: string
      responses:
        '303':
          description: location of the download url

components:
  schemas:
    MediaUpload:
      type: object
      required:
        - mediaMetadata
        - media
      properties:
        media:
          type: string
          format: binary
    MediaUploadResponse:
      type: object
      required:
        - mediaId
      properties:
        mediaId:
          type: string