package: timelines_v2
generate:
  chi-server: true
  embedded-spec: true
  models: true
import-mapping:
  ../../../status/api-definition/openapi.yaml: yatc/status/pkg
output: ./timeline/internal/v2/timelineapi.gen.go